### ISSUE TITLE
Questions about deployment and PR

### ISSUE THREAD

**Issue by datatalking** [hitensam/Library-Management#5]
Hi @hitensam I found your repo today and was curious about expanding this or adapting it to a project I've been building for a while.

1. What database is this setup for in conjunction to the Firebase app?
2. Is this project accepting PR for collaboration or is it closed?
3. It seems like this is for a google cloud instance with firebase, can this be hosted locally or is it online hosted only?
4. I'm hoping I can update or add functionality to your project if it will work with Mysql or postgres database, but I didn't see where it mentioned where it saves the data in the 'db' file.

**Comment by hitensam** [comment]
Hi @datatalking

1. For database we are using Firebase and to work with it in python we are using pyrebase4 (https://github.com/nhorvath/Pyrebase4)

2. Yes this project is open for collaboration.

3. Google Firebase hosted online.

4. The db.py file contains the configuration that is needed to use Firebase.
